#! /usr/bin/env bash

# make sure errors in sourced scripts will cause this script to stop
set -e

HERE=$(readlink -f $(dirname "$0"))

export LD_LIBRARY_PATH=$(readlink -f "$HERE/usr/lib"):$LD_LIBRARY_PATH
export GST_PLUGIN_SYSTEM_PATH=$(readlink -f "$HERE/usr/lib/gstreamer-1.0")
export SAYONARA_SHARE_DIR=$(readlink -f "$HERE/usr/share/sayonara")

case "${XDG_CURRENT_DESKTOP}" in
    *GNOME*|*gnome*|*XFCE*)
        export QT_QPA_PLATFORMTHEME=gtk2
        ;;
esac

exec "$HERE"/usr/bin/sayonara "$@"

