#! /usr/bin/env bash

# make sure errors in sourced scripts will cause this script to stop
set -e

RUNTIME=$(readlink -f $(dirname "$0"))

export LD_LIBRARY_PATH=$(readlink -f "$RUNTIME/usr/lib"):$LD_LIBRARY_PATH
export GST_PLUGIN_SYSTEM_PATH=$(readlink -f "$RUNTIME/usr/lib/gstreamer-1.0")
export GST_PLUGIN_SCANNER=$(readlink -f "$RUNTIME/usr/lib/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner")
export SAYONARA_SHARE_DIR=$(readlink -f "$RUNTIME/usr/share/sayonara")

case "${XDG_CURRENT_DESKTOP}" in
    *GNOME*|*gnome*|*XFCE*)
        export QT_QPA_PLATFORMTHEME=gtk2
        ;;
esac

exec "$RUNTIME"/usr/bin/sayonara "$@"

